name: glowup
description: "A new Flutter project."
publish_to: 'none' 




version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_svg: ^2.0.10+1
  flutter_bloc: ^9.1.1
  flutter_native_splash: ^2.4.6
  get_it: ^8.0.3
  google_maps_flutter: ^2.12.3
  flutter_screenutil: ^5.9.3
  google_sign_in: ^7.0.0
  geolocator: ^14.0.1
  flutter_dotenv: ^5.2.1
  supabase_flutter: ^2.9.1
  table_calendar: ^3.2.0
  url_launcher: ^6.3.1
  easy_localization: ^3.0.7+1
  smooth_page_indicator: ^1.2.1
  cached_network_image: ^3.4.1
  image_picker: ^1.1.2
  animated_toggle_switch: ^0.8.5
  flutter_rating_bar: ^4.0.1
  dotted_border: ^3.1.0
  moyasar: ^2.0.19

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  image_path: "assets/images/logo_glow_up.png"
  android: true
  ios: true


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter_native_splash:
  # turn on for both platforms
  android: true
  ios: true

  # global background color behind the splash
  color: "#FFF5E1"
  # path to your splash image
  color_dark: "#1A1A1A"


  # optional: override for Android 12+ window splash
  android_12:
    image: assets/images/splash.png
    image_dark: assets/images/splash_dark.png
    color: "#FFF5E1"
    color_dark: "#1A1A1A"


flutter:



  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
  - assets/images/
  - assets/svgs/
  - assets/translations/
  - .env

  # - images/a_dot_burr.jpeg
  # - images/a_dot_ham.jpeg
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package
fonts:
  - family: MontserratAlternates
    fonts:
      - asset: Custom_fonts/MontserratAlternates-Thin.ttf
        weight: 100
      - asset: Custom_fonts/MontserratAlternates-ThinItalic.ttf
        weight: 100
        style: italic
      - asset: Custom_fonts/MontserratAlternates-ExtraLight.ttf
        weight: 200
      - asset: Custom_fonts/MontserratAlternates-ExtraLightItalic.ttf
        weight: 200
        style: italic
      - asset: Custom_fonts/MontserratAlternates-Light.ttf
        weight: 300
      - asset: Custom_fonts/MontserratAlternates-LightItalic.ttf
        weight: 300
        style: italic
      - asset: Custom_fonts/MontserratAlternates-Regular.ttf
        weight: 400
      - asset: Custom_fonts/MontserratAlternates-Italic.ttf
        weight: 400
        style: italic
      - asset: Custom_fonts/MontserratAlternates-Medium.ttf
        weight: 500
      - asset: Custom_fonts/MontserratAlternates-MediumItalic.ttf
        weight: 500
        style: italic
      - asset: Custom_fonts/MontserratAlternates-SemiBold.ttf
        weight: 600
      - asset: Custom_fonts/MontserratAlternates-SemiBoldItalic.ttf
        weight: 600
        style: italic
      - asset: Custom_fonts/MontserratAlternates-Bold.ttf
        weight: 700
      - asset: Custom_fonts/MontserratAlternates-BoldItalic.ttf
        weight: 700
        style: italic
      - asset: Custom_fonts/MontserratAlternates-ExtraBold.ttf
        weight: 800
      - asset: Custom_fonts/MontserratAlternates-ExtraBoldItalic.ttf
        weight: 800
        style: italic
      - asset: Custom_fonts/MontserratAlternates-Black.ttf
        weight: 900
      - asset: Custom_fonts/MontserratAlternates-BlackItalic.ttf
        weight: 900
        style: italic
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package


